// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDej3yFST5DwEVaAc3-u3qXIco-6ja-gaE',
    appId: '1:137122248646:web:fa6f5cf47709e4f23f24c7',
    messagingSenderId: '137122248646',
    projectId: 'globalwomenfitness',
    authDomain: 'globalwomenfitness.firebaseapp.com',
    storageBucket: 'globalwomenfitness.appspot.com',
    measurementId: 'G-PCVQ8K2SBS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL08WvX_tTug6Cb5UVZDqJbtujtOzjeeo',
    appId: '1:137122248646:android:d6bf20ee955d5eaf3f24c7',
    messagingSenderId: '137122248646',
    projectId: 'globalwomenfitness',
    storageBucket: 'globalwomenfitness.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqbQwppnHUg6JGmAGN0HIB1ehqEcteYx4',
    appId: '1:137122248646:ios:c0a9611206a4f46b3f24c7',
    messagingSenderId: '137122248646',
    projectId: 'globalwomenfitness',
    storageBucket: 'globalwomenfitness.appspot.com',
    iosClientId: '137122248646-dnsub2bo7nc39fq81np0nac81qufs6i1.apps.googleusercontent.com',
    iosBundleId: 'com.example.gobalWomenFitnessApp',
  );
}
